HYDRA_FULL_ERROR=1 python humanoidverse/train_agent.py \
+simulator=isaacgym \
+exp=motion_tracking \
+domain_rand=NO_domain_rand \
+rewards=motion_tracking/reward_motion_tracking_dm_2real \
+terrain=terrain_locomotion_plane \
+obs=motion_tracking/x2t2_23dof \
+robot=x2_t2/x2_t2_23dof \
+opt=wandb \
num_envs=4096 \
project_name=ASAP \
experiment_name=SingleMotion-jump_1 \
robot.motion.motion_file="custom_data/x2_t2_23dof_retarget_motion_dynamic_adjust/jump_1.pkl" \
rewards.reward_penalty_curriculum=True \
rewards.reward_penalty_degree=0.00001 \
env.config.resample_motion_when_training=False \
env.config.termination.terminate_when_motion_far=True \
env.config.termination_curriculum.terminate_when_motion_far_curriculum=True \
env.config.termination_curriculum.terminate_when_motion_far_threshold_min=0.3 \
env.config.termination_curriculum.terminate_when_motion_far_curriculum_degree=0.000025 \
robot.asset.self_collisions=0